services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: orka
      MONGO_INITDB_ROOT_PASSWORD: orka
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: orka
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["--js"]
    # volumes:
    #   - nats-data:/data
    environment:
      - NATS_SERVER_NAME=orka
      - JS_MAX_MEMORY_STORE=1G
      - JS_MAX_FILE_STORE=10G
