// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/orka-org/orkacore/internal/biz"
	"github.com/orka-org/orkacore/internal/conf"
	"github.com/orka-org/orkacore/internal/data"
	"github.com/orka-org/orkacore/internal/server"
	"github.com/orka-org/orkacore/internal/service"
	"github.com/orka-org/orkacore/pkg/tokens"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	tokenFactory := tokens.NewTokenProvider(bootstrap)
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo, err := data.NewUserRepo(dataData, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userUsecase := biz.NewUserUsecase(userRepo, logger)
	authUsecase := biz.NewAuthUsecase(tokenFactory, userUsecase, logger)
	authServiceService := service.NewAuthServiceService(authUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, authServiceService, logger)
	httpServer := server.NewHTTPServer(confServer, authServiceService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
